---
#- include_tasks: reboot.yml

- name: copy config.yaml template
  template:
    src: ../templates/config.yaml
    dest: /root/config.yaml
  tags: test_ad

- include_tasks: master_only.yml
  when: ansible_hostname == groups['master'][0]

- include_tasks: minion.yml
  when: ansible_hostname != groups['master'][0]

- name: copy pki files
  copy:
    src: "../files/pki/{{ item }}"
    dest: "/etc/kubernetes/pki/"
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
  when: ansible_hostname != groups['master'][0]

- name: create kubernetes home repository config
  file:
    path: /root/.kube
    state: directory
    mode: 0755

- name: copy file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: 0755
    remote_src: yes


#- name: copy dashboard template
#  template:
#    src: ../../templates/kubernetes-dashboard.yaml
#    dest: /root/kubernetes-dashboard.yaml

#- name: deploy dashboard
#  shell: kubectl apply -f /root/kubernetes-dashboard.yaml
