---
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: {{ ansible_default_ipv4.address }}
etcd:
  endpoints:
    {% for host in vars['play_hosts'] %}

        hostvars[host]['ansible_interfaces'] | difference(['docker0','lo']) | first
      - https://{{ hostvars[host]['ansible_'] }}:2379
    {% endfor %}

  caFile: /etc/kubernetes/pki/etcd/ca.pem  
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: {{ pod_network_cidr }}
apiServerCertSANs:
- {{ virtual_ip }}
apiServerExtraArgs:
  apiserver-count: {{ vars['play_hosts'] | length }}
